Feature/random profile
SpartaEnergizerTeam/movie-site pull request #15
Opened 2024-05-04 11:00 UTC by LeLu815

프로필 생성 페이지

1. 랜덤 이미지 생성 
2. 유저 아이디
3. 유저 비밀번호

해당 값을 로컬에 저장.
로컬에 정보가 있으면 불러옴.

2024-05-04 11:15 UTC, 1eeyerin requested changes

2024-05-04 11:15 UTC, 1eeyerin commented on css/animate.css
> +@charset "UTF-8"; /*!
주석 시작점은 2번째줄부터 부탁드립니다!

2024-05-04 11:15 UTC, 1eeyerin commented on css/profile.css
> +}
이부분 제거 부탁드립니다!

2024-05-04 11:15 UTC, 1eeyerin commented on css/profile.css
> +
개행 제거 부탁드립니다!

2024-05-04 11:15 UTC, 1eeyerin commented on css/profile.css
> +  border-radius: 999px;
999px이여야하는 이유가 있을까요?

2024-05-04 11:15 UTC, 1eeyerin commented on css/profile.css
> +  background: #5e5e5e !important;
!important 없이 사용이 어려울까요?

2024-05-04 11:15 UTC, 1eeyerin commented on css/profile.css
> +
개행 제거 부탁드립니다!

2024-05-04 11:15 UTC, 1eeyerin commented on js/profile.js
> +const background_color_list = [
상수임을 쉽게 인지하기 위해 대문자로 작성하는 규칙을 적용하면 어떨까 제안드립니다~
https://stackoverflow.com/questions/34732630/all-caps-constants-in-javascript-and-requireds-and-imports

2024-05-04 11:15 UTC, 1eeyerin commented on js/profile.js
> +var disabled = false;
var 사용 지양 부탁드립니다!

2024-05-04 11:15 UTC, 1eeyerin commented on js/profile.js
> +  // mouth 9
주석이 의미가 없다면 제거 부탁드립니다!

2024-05-04 11:15 UTC, 1eeyerin commented on js/profile.js
> +  window.location.href = returnUrl;
이부분은 a 태그로 대체가 가능한데 js 로 쓰시는 이유가 따로 있으신지 궁금합니다!
시맨틱적인 사이트를 지향할 수 있도록 html로 명확한 페이지 이동이라는 의미를 가진 a 태그를 덧대어 사용하는 것을 권장 드립니다 :)

2024-05-04 11:15 UTC, 1eeyerin commented on js/profile.js
> +  window.location.href = returnUrl;
위와 동일합니다

2024-05-04 11:15 UTC, 1eeyerin commented on profile.html
> +          <button id="cancel" class="btn cancel">취소</button>
타입 명시 부탁드립니다 button 태그의 기본 type은 submit 입니다.

2024-05-04 11:22 UTC, LeLu815 commented on css/profile.css
> +  background: #5e5e5e !important;
뺐습니다.

2024-05-04 11:22 UTC, LeLu815 commented on css/animate.css
> +@charset "UTF-8"; /*!
해당 라인 삭제했습니다

2024-05-04 11:23 UTC, LeLu815 commented on css/profile.css
> +}
제거했습니다

2024-05-04 11:23 UTC, LeLu815 commented on css/profile.css
> +
제거했습니다.

2024-05-04 12:42 UTC, LeLu815 commented on css/profile.css
> +  border-radius: 999px;
큰 의미는 없습니다 그냥 계산하기가 좀 귀찮아서...ㅋ
그 테일윈드  rounded-full 인가 거기에서 999픽셀이라서 값으로 넣었습니다.

2024-05-04 12:42 UTC, LeLu815 commented on js/profile.js
> +var disabled = false;
수정했습니다

2024-05-04 12:49 UTC, LeLu815 commented on js/profile.js
> +  window.location.href = returnUrl;
넵 수정했습니다

2024-05-04 12:53 UTC, LeLu815 commented on js/profile.js
> +  // mouth 9
의미있는 부분만 남기고 삭제했씁니다

2024-05-04 14:35 UTC, 1eeyerin requested changes

2024-05-04 14:35 UTC, 1eeyerin commented on profile.html
> +            placeholder="username"
placeholder는 고객이 placeholder 목적에 맞게 쉽게 인지할 수 있도록 한글 가이드 문구가 들어가면 어떨까요?
ex) 아이디를 입력해주세요

2024-05-04 14:35 UTC, 1eeyerin commented on profile.html
> +            placeholder="password"
동일합니다!

2024-05-04 14:35 UTC, 1eeyerin commented on profile.html
> +          </a>
a 태그와 button은 의미가 다릅니다, 중첩 사용을 지양 부탁드립니다!
혹시 취소를 하면 index.html로 이동하는 이유가 있을까요?

2024-05-04 14:37 UTC, 1eeyerin commented
![image](https://github.com/SpartaEnergizerTeam/movie-site/assets/40863185/7bcbd6d7-71a7-4231-b524-37d21688a997)
접혀진 부분의 코멘트도 확인 부탁드려요!

2024-05-05 04:11 UTC, LeLu815 commented on profile.html
> +            placeholder="password"
수정했습니다

2024-05-05 04:11 UTC, LeLu815 commented on profile.html
> +            placeholder="username"
수정했습니다

2024-05-05 04:12 UTC, LeLu815 commented on profile.html
> +          </a>
메인 화면으로 이동하는 용도입니다. 
인덱스가 메인화면인것 같아서요

뒤로 가면 우리 웹사이트를 아에 나가버리는 경우가 있는대
브라우저에서 관리하는 히스토리 스택은 직접접근이 불가하다고 해서
사이트를 아에 나가게 할바에는 그냥 홈으로 이동시키고자 했습니다.

2024-05-05 04:13 UTC, LeLu815 commented on css/profile.css
> +
제거 완료했씁니다

2024-05-05 04:32 UTC, LeLu815 commented on profile.html
> +          </a>
a와 btn의 차이에 대해서 생각해보지 않았었는데 덕분에 의미론적 마크업에 대해서 생각해보게 되었습니다.

btn을 a로 변경했습니댜

2024-05-05 04:33 UTC, LeLu815 commented on js/profile.js
> +const background_color_list = [
수정 완료했습니다

2024-05-06 00:48 UTC, 1eeyerin commented on profile.html
> +          <a href="index.html" id="cancel" type="button" class="btn cancel"
type 지워주세요!

2024-05-06 00:48 UTC, 1eeyerin commented on profile.html
> +              style="width: 120px; height: 120px"
인라인 스타일로 지정하신 이유가 있을까요? 관리 포인트가 늘어나기에 특별한 이유가 없다면 html에서 styling을 지양 부탁드립니다!

2024-05-06 00:48 UTC, 1eeyerin commented on profile.html
> +        <button class="createBtn" id="createRandomBtn">랜덤 생성</button>
이부분도 type=button 명시 부탁드립니다!

2024-05-06 00:49 UTC, 1eeyerin approved these changes
추가 코멘트만 수정 부탁드립니다!

2024-05-06 01:42 UTC, LeLu815 commented on profile.html
> +        <button class="createBtn" id="createRandomBtn">랜덤 생성</button>
넵

2024-05-06 01:43 UTC, LeLu815 commented on profile.html
> +          <a href="index.html" id="cancel" type="button" class="btn cancel"
지웠습니다

2024-05-06 01:45 UTC, merged

2024-05-06 01:52 UTC, LeLu815 commented on profile.html
> +              style="width: 120px; height: 120px"
스타일링 바꿨습니다