Feature/create detail
SpartaEnergizerTeam/movie-site pull request #24
Opened 2024-05-06 09:36 UTC by Ahnjonghyun87

detail.js에서 import 해온 detail 정보에 인물 관련 정보가 없어서 

절취선 밑에 따로 api를 가져오는 함수를 gpt4파워로 썼습니다

현재는 상세정보와 인물 정보가 id 1094844로 맞춰진 상태인데

메인화면에서 카드를 클릭해서 가져오는 id 값이 밑의 credit api의 fetch에서도 동일하게 바꿔주는 작업까진 해야 합니다

2024-05-06 11:21 UTC, 1eeyerin requested changes

2024-05-06 11:21 UTC, 1eeyerin commented on css/detail.css
> +    scrollbar-color: #a5a5a5 #1b1b1b;
이부분, 예은님이 작업해주셔서 공통으로 빼면 전체 적용될 것이기 때문에 제거해주셔도 좋을 것 같습니다!

2024-05-06 11:21 UTC, 1eeyerin commented on css/detail.css
> +.image-box img {
전체적으로 classname이 겹치지 않도록 부모 element에 class 주어 앞에 붙여주실 수 있나요?
저도 같은 페이지이기 때문에 class name이 겹친다면 부작용이 생길 수 있습니다!

2024-05-06 11:21 UTC, 1eeyerin commented on css/detail.css
> +    margin-left: -430px;
이부분 margin-left 하는 이유가 궁금합니다!

2024-05-06 11:21 UTC, 1eeyerin commented on css/detail.css
> +    color: #fff;
컬러코드는 헥사 방식으로 #ffffff 6자리로 통일 부탁드립니다

2024-05-06 11:21 UTC, 1eeyerin commented on css/detail.css
> +    background-size: 1240px auto;
부모 너비가 1240이기 때문에, 유지보수 관점에서는 100% auto 나 cover 사용을 추천드립니다!

2024-05-06 11:21 UTC, 1eeyerin commented on css/detail.css
> +    color:#fff
이부분도 컬러값 통일 부탁드립니다!

2024-05-06 11:21 UTC, 1eeyerin commented on css/detail.css
> +    font-size: 0;
혹시 여기에 font-size:0을 하신 이유가 있을까요?

2024-05-06 11:21 UTC, 1eeyerin commented on css/detail.css
> +    /* align-items: center; /*수평정렬, 원본에는 수평정렬 썼는데 저는 공유버튼이랑 높낮이 맞추려고 껐습니다*/
필요 없는 것이라면 제거가 좋아보입니다!

2024-05-06 11:21 UTC, 1eeyerin commented on css/detail.css
> +
개행 제거 부탁드립니다~

2024-05-06 11:21 UTC, 1eeyerin commented on css/detail.css
> +
동일합니다

2024-05-06 11:21 UTC, 1eeyerin commented on css/detail.css
> +    /*padding-top: 20px;*/
필요 없다면 제거 부탁드립니다!

2024-05-06 11:21 UTC, 1eeyerin commented on detail.html
> +                   <!---<source srcset=".img/detail/1713512289000104275.webp 1x,.img/detail/1713512289000104275.webp 1.7x,.img/detail/1713512289000104275.webp 2.5x" type="image/webp">--->
필요없다면 제거 부탁드립니다~

2024-05-06 11:21 UTC, 1eeyerin commented on js/detail.js
> +//});
필요 없는 주석은 제거 부탁드립니다~

2024-05-06 11:41 UTC, Ahnjonghyun87 commented on js/detail.js
> +//});
수정했습니다

2024-05-06 11:42 UTC, Ahnjonghyun87 commented on detail.html
> +                   <!---<source srcset=".img/detail/1713512289000104275.webp 1x,.img/detail/1713512289000104275.webp 1.7x,.img/detail/1713512289000104275.webp 2.5x" type="image/webp">--->
저게 원본에는 있었는데 무슨 역할을 하는지 몰라서 주석처리했습니다~ 삭제 완료요

2024-05-06 11:43 UTC, Ahnjonghyun87 commented on css/detail.css
> +    /*padding-top: 20px;*/
/*padding-top: 20px;*/ 이 주석 삭제했습니다

2024-05-06 11:45 UTC, Ahnjonghyun87 commented on css/detail.css
> +
.detail-view-content-arena  {

    padding-bottom: 60px;

}

제거해도 차이가 없어서 삭제했습니다

2024-05-06 11:47 UTC, Ahnjonghyun87 commented on css/detail.css
> +
.preview-dsc {
    margin-top: 18px;
    font-size: 16px;
    color: #a5a5a5;
    line-height: 24px;
}

이렇게 수정했는데 맞나요?

2024-05-06 11:48 UTC, Ahnjonghyun87 commented on css/detail.css
> +    background-size: 1240px auto;
background-size: cover; 이걸로 바꿨습니다

2024-05-06 11:51 UTC, Ahnjonghyun87 commented on css/detail.css
> +    color: #fff;
.video-button {
    width: 360px;
    height: 48px;
    border-radius: 12px;
    background-color: #1351f9;
    font-size: 16px;
    color: #ffffff;
    margin-right: 50px; /* 오른쪽 여백 추가 */
}
변경했습니다

2024-05-06 11:53 UTC, Ahnjonghyun87 commented on css/detail.css
> +    margin-left: -430px;
text-align: center;만 먹이면 중앙에는 오는데 제가 원하는 만큼 왼쪽으로 안오더라구요 원본 수사반장 1958처럼
중앙정렬인데 화면에 왼쪽으로 치우치게끔 하려고 마이너스로 마진 먹이니까 이쁘게 떴습니다 이건 다른 영화 id 값을 줘도 이쁘게 떠서 안바꿔도 될거 같습니다

2024-05-06 11:54 UTC, Ahnjonghyun87 commented on css/detail.css
> +    scrollbar-color: #a5a5a5 #1b1b1b;
스크롤 css 제거 했습니다

2024-05-06 12:01 UTC, Ahnjonghyun87 commented
.detail-view-content-area .detail-view-box .detail-info-table .genre {
    display: inline-block;
    color: #fff;
    vertical-align: top;
}  220번째줄. 작동을 안해서 삭제했습니다

2024-05-06 12:26 UTC, Ahnjonghyun87 commented on css/detail.css
> +.image-box img {
앞에 class네임 다 먹이면서 최대한 다른 class name이랑 안겹치도록 했습니다 확인 부탁드려요

2024-05-06 12:53 UTC, Ahnjonghyun87 commented on css/detail.css
> +    /* align-items: center; /*수평정렬, 원본에는 수평정렬 썼는데 저는 공유버튼이랑 높낮이 맞추려고 껐습니다*/
지웠습니다

2024-05-06 12:55 UTC, Ahnjonghyun87 commented on css/detail.css
> +    font-size: 0;
수정했습니다

2024-05-06 12:55 UTC, Ahnjonghyun87 commented on css/detail.css
> +    color:#fff
통일했습니다

2024-05-07 02:02 UTC, yeeunseo-dev approved these changes
너무 고생하셨습니다..
새로운 페이지라 난이도가 있었을텐데 아주 깔끔하게 적어주셔서 잘 읽었습니다 :)

2024-05-07 02:02 UTC, yeeunseo-dev commented on css/detail.css
> +    z-index: 10;
z-index값이 어떤 역할하는지 궁금합니다! 저는 큰 차이없어서 지우기도 했어서욤

2024-05-07 02:02 UTC, yeeunseo-dev commented on css/detail.css
> +
요기 한줄 띄워져있슴다

2024-05-07 03:21 UTC, ARMJONG approved these changes
JS코드 일일히 주석으로 달아주셔서 이해하기 쉬웠습니다!

2024-05-07 07:32 UTC, Ahnjonghyun87 commented on css/detail.css
> +    z-index: 10;
::before라는 효과 때문에  썼습니다  저도 웨이브 클론 css하면서 알게된건데 예를들면 얇은 셀로판지 두게 깔아두고 z 값으로  a와 b중 어떤게 더 앞으로 부각될지 조절하는 값이라고 합니다

2024-05-07 07:32 UTC, Ahnjonghyun87 commented on css/detail.css
> +
수정했습니다~

2024-05-07 07:33 UTC, Ahnjonghyun87 commented
> JS코드 일일히 주석으로 달아주셔서 이해하기 쉬웠습니다!

감사합니다 암종현님도 따봉스

2024-05-07 07:36 UTC, merged