feat : 팝업 기능 구현
SpartaEnergizerTeam/movie-site pull request #26
Opened 2024-05-06 14:28 UTC by LeLu815

popup.js
popup.css
index.html 파일 안에 구현함.
(바디를 화면 전체로 확장하기 위해 부득히하게 잠깐 inline 스타일로 100vh,vw 설정함)

일주일간 보지 않기를 누르고 삭제하면 1주일 만료로 쿠키에 저장됨
일주일간 보지 않기를 누르지 않고 삭제하면 새로고침시 팝업창이 다시 생성됨

2024-05-07 01:50 UTC, Ahnjonghyun87 approved these changes
l g t mmmmmm

2024-05-07 02:08 UTC, yeeunseo-dev approved these changes
코드를 다 이해하진 못했지만
잘 읽었습니다 :)

2024-05-07 02:08 UTC, yeeunseo-dev commented on css/popup.css
> +.popup-checkbox input[type="checkbox"] {
요런방법도 있군요

2024-05-07 02:08 UTC, yeeunseo-dev commented on index.html
> +      rel="stylesheet"
줄 띄워져있습니당

2024-05-07 02:08 UTC, yeeunseo-dev commented on index.html
> +    />
여기도 줄 띄워져 있습니다!

2024-05-07 02:15 UTC, 1eeyerin requested changes

2024-05-07 02:15 UTC, 1eeyerin commented on css/popup.css
> +  width: 508px;
<img width="760" alt="image" src="https://github.com/SpartaEnergizerTeam/movie-site/assets/40863185/a063bff0-c7fb-44ed-affa-7126634e4030">

혹시 이 여백은 의도하신걸까용?

2024-05-07 02:15 UTC, 1eeyerin commented on index.html
> +      <screen class="main-screen">
`<screen>` 태그가 실제로 있는 태그인가요?

2024-05-07 02:15 UTC, 1eeyerin commented on css/popup.css
> +
개행 제거 부탁드립니다.

2024-05-07 02:15 UTC, 1eeyerin commented on css/popup.css
> +  z-index: 2200;
z-index는 최대한 낮은 값을 작성 부탁드립니다! z-index 관리포인트가 늘어날 수록 다른 곳에서는 z-index를 임계값까지 써야하는 이유가 계속 발생하기 때문입니다.

2024-05-07 02:15 UTC, 1eeyerin commented on css/popup.css
> +  z-index: 2000;
동일합니다. 현재 상황에서는 50이나 100도 동일한 효과를 구현할 수 있다고 생각됩니다.

2024-05-07 02:15 UTC, 1eeyerin commented on index.html
> +  <body style="height: 100vh; width: 100vw">
지금은 없어도 동일한 동작을 하는 것 같습니다!

2024-05-07 03:29 UTC, ARMJONG commented on index.html
> +              src="https://image.wavve.com/v1/thumbnails/0_0_20_80/service30/crm/auth_firstbenefit_layerpopup_pc.jpg"
Img 아래 줄 띄워짐

2024-05-07 03:48 UTC, ARMJONG approved these changes
주석처리 잘 해주셔서 이해가 편했습니다

2024-05-07 09:57 UTC, 1eeyerin requested changes

2024-05-07 09:57 UTC, 1eeyerin commented on index.html
> +    <script defer src="./js/index.js" type="module"></script>
index.js 중첩됩니다 :)

2024-05-08 02:18 UTC, Ahnjonghyun87 approved these changes
popup.js에서 많이 배웠습니다 고생하셨습니다

2024-05-08 05:41 UTC, Ahnjonghyun87 approved these changes
고생하셨습니다 lgtm!

2024-05-08 12:29 UTC, 1eeyerin approved these changes

2024-05-08 12:59 UTC, merged